### ISSUE TITLE
Can't integrate with alpine js 

### ISSUE THREAD

**Issue by fernandokbs** [stimulusreflex/stimulus_reflex#567]
# Bug Report

## Describe the bug

I was testing the library following the hello world example, but I have some random errors for example after click in a button and update the view, several dropdowns opens, this behavior happens using,  Stimulus Dropdown and alpine js. 
Any updates?

## To Reproduce

Just create the hello world example and add the alpinejs  cnd

## Expected behavior

A few things I'd like:
* Integration with alpine js
* Integration with other stimulus libraries

## Screenshots or reproduction
In this case when I click the increment button, my dropdown opens
<img width="1120" alt="Captura de Pantalla 2022-01-03 a la(s) 10 37 59" src="https://user-images.githubusercontent.com/17089683/147956398-1adc3107-06a7-4b0d-bca8-5050803039f1.png">

### StimulusReflex

- Gem: [3.4]
- Node package: [3.4.1]

### External tools

- Ruby: [2.6.4]
- Rails: [6.0.0]
- Node: [12.4.0]

### Browser

- Browser [chrome, safari]
- Version [22]

**Comment by leastbad** [comment]
Hello, Fernando. Happy to help, although technically this is a support question, not an issue. We offer free, 24/7 support via Discord on our server: https://discord.gg/stimulus-reflex

In the meantime, you can configure support for Alpine by following these instructions: https://cableready.stimulusreflex.com/customization#shouldmorph-callbacks

Specifically, you want to check out the 2nd use case which should resolve Alpine issues.

Please join us on Discord and we can answer any other questions you might have.

**Comment by phacks** [comment]
I ran into similar issues and figured out a solution that worked for us, which I [shared](https://discord.com/channels/629472241427415060/733725826411135107/984417165006471188) in the Discord linked above. I’ll cross-post it here as this issue might also be a good place for it:

There were two issues:

1. The shouldMorph callback example in the SR docs (https://cableready.stimulusreflex.com/customization#shouldmorph-callbacks) is not compatible with AlpineJS v3.x (which does not use `.__x` anymore, but the equally confusing `._x_dataStack`). Here’s a snippet that works:

```javascript
const enableAlpine = (options, fromEl, toEl) => {
  if (fromEl._x_dataStack) {
    window.Alpine.clone(fromEl, toEl);
  }
  return true;
};
```

2. Now came the real head-scratcher. With the above, I had a teeny tiny repro on Codepen that made Morphdom + Alpine work like a charm, but throwing SR into the mix caused issues. It turned out that SR didn’t properly parse the nonstandard @-attributes (like @click) used in Alpine, and so the DOM post-morph had “broken” Alpine attributes. Stumbled upon an SR issue (https://github.com/stimulusreflex/stimulus_reflex/issues/435) that clearly explained the reason for that, and the fix: changing all of those into `x-on:click` did the trick!
