### ISSUE TITLE
docs recommend hiredis gem along with incompatible redis version 

### ISSUE THREAD

**Issue by robinboening** [stimulusreflex/stimulus_reflex#710]
The current docs at https://docs.stimulusreflex.com/appendices/deployment.html#use-redis-as-your-cache-store recommend installing `redis >= 4.0`.

```
gem "redis", ">= 4.0", require: ["redis", "redis/connection/hiredis"]
gem "hiredis"
```

This allows redis 5.x which doesn't include `redis/connection/hiredis` anymore and therefore breaks.

From what I understand `redis-client`  (`redis` dependency) works together with a gem called `hiredis-client` which is included in the `redis-client` repository on github: https://github.com/redis-rb/redis-client/tree/master/hiredis-client

What is the recommended solution?

**Comment by marcoroth** [comment]
Hey @robinboening, thanks for the issue!

Personally I haven't been using the `hiredis` gem in any of my applications, so I cannot really provide any recommendations, which is why I removed it for now. 

It seems that the redis and redis-client have changed quite a bit since this part of the docs was written, so it's probably very different now.

I updated the docs to reflect this in https://github.com/stimulusreflex/stimulus_reflex/commit/c363843f720100f203c77e1ffd4b6b0b3eeb059a.

If anybody has has a recommended way of how they use `hiredis` for their Rails Session Store I'd love to hear it!
